### ISSUE TITLE
Windows 10 with Msys64 null windowsHome with version 3.5.1

### ISSUE THREAD

**Issue by mondain** [maven-nar/nar-maven-plugin#248] opened 2016-11-01 19:48 UTC
Version 3.4.0 was used successfully, but after upgrading to version 3.5.1 I can't build and get an error at line 128 in https://github.com/maven-nar/nar-maven-plugin/blob/master/src/main/java/com/github/maven_nar/Msvc.java 
Inside the shell, executing `env` yields the properties expected and `SYSTEMROOT` is specified with a value of `C:\WINDOWS`. I looked over `Msvc.java` and it appears to look only for `SystemRoot` in `init()` could that be the issue?

https://github.com/maven-nar/nar-maven-plugin/blob/master/src/main/java/com/github/maven_nar/Msvc.java#L202

**Comment by mondain** [comment] 2016-11-01 20:09
Just tested version 3.5.0 and it works, so its for sure a bug in 3.5.1

**Comment by ctrueden** [comment] 2016-11-01 23:09
@mondain If you have time, you can use `git bisect` to find the exact offending commit. Or use `git blame` on the code you mention above to check the latest commits surrounding that logic and read the justifications.

**Comment by eyalg1972** [comment] 2017-01-18 08:20
I just created a Pull request to resolve it (Fixed on my local repository)

**Comment by ctrueden** [comment] 2017-05-09 20:32
@eyalg1972 Was that PR one of the ones that has now been merged? Or one that is still outstanding? Could you please cross-link it here? And if it was merged, close this issue?

**Comment by eyalg1972** [comment] 2017-05-10 04:36
The issue was not mine.

But it was resolved before I managed to the the fix, I just had not had the
most updated code at that time, so the error got reproduce.

You can ignore my comment there.

Eyal

**Comment by ctrueden** [comment] 2017-05-10 14:22
@eyalg1972 OK, thanks.

**Closed by ctrueden** 2017-05-10 14:22 UTC

**Comment by mondain** [comment] 2017-05-10 15:20
Which version of the plugin is this fixed in?

**Comment by ctrueden** [comment] 2017-05-10 15:25
@mondain There has not been a new release since 3.5.1. Could you please test with the latest master? If it still occurs, then please reopen this issue. Thank you very much!

**Comment by mondain** [comment] 2017-05-10 16:25
Sure, I'll give it a go, thanks.
