### ISSUE TITLE
upgrading NAR from 3.2.3 to 3.5.1 but MSVC version not detected

### ISSUE THREAD

**Issue by bcopy** [maven-nar/nar-maven-plugin#284] opened 2017-06-27 09:37 UTC
Hello,

I'm trying to upgrade my C++ project from NAR plugin 3.2.3 to 3.5.1, but in doing so, I get :

`[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.5.1:nar-compile (default-nar-compile) on project dim-static: Execution default-nar-compile of goal com.github.maven-nar:nar-maven
-plugin:3.5.1:nar-compile failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.5.1:nar-compile (default-nar-compile) on project dim-static: `

`Execution default-nar-compile of goal com.github.maven-nar:nar-maven-plugin:3.5.1:nar-compile failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
(...)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-nar-compile of goal com.github.maven-nar:nar-maven-plugin:3.5.1:nar-compile failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
`

`Caused by: java.lang.NullPointerException
        at com.github.maven_nar.Msvc.configureCCTask(Msvc.java:128)
        at com.github.maven_nar.NarCompileMojo.createLibrary(NarCompileMojo.java:218)
        at com.github.maven_nar.NarCompileMojo.narExecute(NarCompileMojo.java:453)
        at com.github.maven_nar.AbstractNarMojo.execute(AbstractNarMojo.java:195)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more`

It seems that a version parameter is required but I can't seem to find examples of where to specify it... plus it wasn't required with v 3.2.3 of the plugin.

What should I do to fix it ?

**Comment by Andy--S** [comment] 2017-07-03 15:39
Same here but I think im running 3.5.0 .  There must be a simple solution,

**Comment by dproteus13** [comment] 2017-07-05 03:21
I don't suppose either of you could share your offending POM? Or recreate
the issue with a minimal, complete example?

**Comment by Andy--S** [comment] 2017-07-07 04:25
Ill see what I can put together.

**Comment by ctrueden** [comment] 2017-08-17 19:21
@Andy--S @bcopy Any further info?

**Comment by mschoudry** [comment] 2017-08-29 16:43
try this
`<configuration>
....
<linker><name>msvc</name></linker>
....
</configuration>`

**Comment by GregDomjan** [comment] 2017-10-12 05:14
The configuration would be like
	<configuration>
		<os>Windows</os>
		<msvc>
			<version>14.0</version>
			<windowsSdkVersion>10.0.15063.0</windowsSdkVersion>
		</msvc>

If no specific compiler or platform SDK version is specified, then it should try to take the latest version it finds or the default preconfigured in the environment.   Neither of these is best way to have a reproducible build.

In 3.5.1 release 
java.lang.NullPointerException at com.github.maven_nar.Msvc.configureCCTask(Msvc.java:128) at com.github.maven_nar.NarCompileMojo.createLibrary(NarCompileMojo.java:218) at 

refers to 
      [envVariable.setValue(this.windowsHome.getAbsolutePath());](https://github.com/maven-nar/nar-maven-plugin/blob/nar-maven-plugin-3.5.1/src/main/java/com/github/maven_nar/Msvc.java#L128)

Seems like windowsHome wasn't found?  
On brief check, it would remain unset if it's not a windows/msvc

**Comment by Andy--S** [comment] 2017-10-18 05:05
Im sorry I couldnt comply, but 3.5.2 passes 'validation' phase prior to compile now. thanks!
vs 2017

**Comment by ctrueden** [comment] 2017-11-02 21:17
Thanks for the feedback @Andy--S. I'll close this issue since it sounds like 3.5.2 is working for you. Please reopen if the issue persists.

**Closed by ctrueden** 2017-11-02 21:17 UTC
