### ISSUE TITLE
Enhancement - The nar plugin should provide an option to restrict dependencies to direct dependencies only

### ISSUE THREAD

**Issue by aciaccio** [maven-nar/nar-maven-plugin#280] opened 2017-05-22 17:48 UTC
It is desirable for a project to specify strictly those dependencies it needs and none other. Consider the following case:

Project A depends on static library B and shared library C. 

Shared library C also depends on static library B.

Project A can invoke APIs from B (directly, not transitively via C) and C because NAR accumulates every dependency (transitive and direct) at compile/link time even if Project A does not specify B as one of it's direct dependencies (i.e. in Project A's pom.xml). In this way if C was ever refactored to NOT depend on B then downstream projects (Project A for instance) will now fail to build and any audits to determine B's consumption would be obscured.

To help force a more constrained dependency strategy (i.e. being complete about your dependencies) a flag should be added to restrict a project's dependencies to only those that the project depends on. 

For instance, in the example above Project A must specify BOTH Project B and Project C as dependencies. If, for example, Project A specified C but NOT B as a dependency then B would not be included in the compilation/linking phase and should cause Project A's build to fail.

**Comment by sdedwards** [comment] 2017-05-25 12:42
There is no need for this feature in nar-maven-plugin because Maven itself provides everything you need to control your dependencies. Take a look at how to use  the ["optional" and "excludes" dependencies](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) features.

In your example, the pom.xml of shared library C should declare the dependency on static library B as "optional" because the API of B should not be exposed to users of C. Doing this will prevent Maven including B in project A's dependency list by default unless of course project A wants to include B explicitly. This is how you should manage internal components of shared libraries.

Dependency "exclusions" can be used as a last resort if you have no control over Project C. In Project A you can simply exclude B from the dependency tree and NAR will ignore it.

**Comment by GregDomjan** [comment] 2017-05-26 08:53
It seems like your trying to force a method of resolving poor documentation hygiene through breaking build.  

Make it a bit more complexe/complete
Project A & shared library C both depend on static library B and shared library D. 
A also depends on C.  
D also depends on other things like static E
B also depends on other things like static F

To compile A you need A,C,B,D,F
To test A you need A,C,D to run

if C needs a newer B, then depending on usage maybe A should change or not.
if C needs a newer D, A should probably use the same... 
  with ref specified in A and C to D means you have to resolve conflict
  with ref only specified in C to D means you have potential instability in A if C changes with identified conflict... 

Similar to `<optional>` another method to manage transitive inclusion may be to use `<scope>provided</scope>` . We typically use this whenever a static library is included into some final binary module.  If the usage in C of static lib B was intended to be internal only, then I would mark it provided, and this would help your scenario of ensuring A using B needs to specify itself.  Even if part of B became part of the public API of C I think this method is still appropriate, but you might also copy headers from B into public api of C.

**Comment by aciaccio** [comment] 2017-06-01 18:46
This change provides value in that it enables a parent pom to force the
build constraints we're discussing instead of changing every pom's
dependency blocks to include 'optional', 'provided', or 'excludes'. This
may not be a big deal for many users of maven-nar if they don't have a
large, complicated set of dependencies. For us it's a little bigger deal.
We're building an entire native code enterprise (middleware, server
framework, service executables) using maven nar and we would like to make a
way to force other teams (there are dozens, over 100 engineers) to respect
those constraints in a programmatic way so we have some rules we can hang
our hats on. If it makes any difference I have the enhancement completed
including a suite of automated tests. This enhancement is hidden behind a
flag (at the 'configuration' level in nar's plugin section) so it will not
effect the standard nar behavior. With your permission I can submit a pull
request for these changes. I submit to your folks judgement on if this
change belongs in the nar plugin.

**Comment by ctrueden** [comment] 2017-06-01 19:52
> It is desirable for a project to specify strictly those dependencies it needs and none other.

I agree; the `dependency:analyze` goal is useful for Java projects to test whether this holds true.

> To help force a more constrained dependency strategy (i.e. being complete about your dependencies) a flag should be added to restrict a project's dependencies to only those that the project depends on.
>
> For instance, in the example above Project A must specify BOTH Project B and Project C as dependencies. If, for example, Project A specified C but NOT B as a dependency then B would not be included in the compilation/linking phase and should cause Project A's build to fail.

In Java land, if Maven did that (or had an option to do that), it would generally cause problems. Suppose that Project A uses API from C, but not B, and as such, declares only C as dependency. This is fine and good. But if you try to build A with only C on the classpath, but not B, then you will in many cases receive compilation errors like `The type foo.Bar cannot be resolved. It is indirectly referenced from required .class files`. I am no expert on native code, but can this sort of thing happen when compiling or linking native libraries? If so, then I fear your scheme may not work as intended?

> We're building an entire native code enterprise (middleware, server
framework, service executables) using maven nar and we would like to make a
way to force other teams (there are dozens, over 100 engineers) to respect
those constraints in a programmatic way so we have some rules we can hang
our hats on. If it makes any difference I have the enhancement completed
including a suite of automated tests. This enhancement is hidden behind a
flag (at the 'configuration' level in nar's plugin section) so it will not
effect the standard nar behavior.

All of that certainly makes a huge difference in my view. I would be inclined to merge any such patch (adds functionality you need for a real-world use case, makes it configurable, and tests it well) without hesitation, as long as the patch is reasonably sized and clean.

> With your permission I can submit a pull request for these changes.

Please go for it!

> I submit to your folks judgement on if this change belongs in the nar plugin.

@GregDomjan @sdedwards If you still have strong reservations, then by all means, let's discuss further before proceeding. As long as everyone is actively discussing and things are moving forward, it is worth it. Hopefully we can reach a consensus in a reasonable time frame.

**Comment by ctrueden** [comment] 2017-08-17 20:23
Fixed by the merge of #283.

**Closed by ctrueden** 2017-08-17 20:23 UTC
